import '@assets/globals.css';
import { Inter } from 'next/font/google';
import GlobalProviders from '@/providers/global';
import Header from '@components/header';
import Footer from '@/components/footer';
import Sidebar from '@/components/sidebar';
import { MenuProvider } from '../providers/menu';
import Main from '../components/main';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={ `${inter.className} h-screen`}>
        <GlobalProviders>
          <MenuProvider>
            <Header />

            <Sidebar />
          </MenuProvider>

          <Main>
            { children }
          </Main>

          <Footer />
        </GlobalProviders>
      </body>
    </html>
  )
}
