'use client'

import '@assets/globals.css';
import { Inter } from 'next/font/google';
import GlobalProviders from '@/providers/global.provider';
import Header from '@/components/header.component';
import Footer from '@/components/footer.component';
import { MenuProvider } from '@/providers/menu.provider';
import Main from '@/components/main.component';
import Sidebar from '@/components/sidebar.component';
import ModalContainer from '@components/modal-container.component';
import { useContext } from 'react';
import { AuthContext } from '../contexts/auth.context';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const { isSignedIn } = useContext(AuthContext);

  return (
    <html lang='en' suppressHydrationWarning={true}>
      <body className={ `${inter.className} h-screen`}>
        <GlobalProviders>
          <MenuProvider>
            { isSignedIn ? (
              <>
                <Header />

                <Sidebar />
              </>
            ) : <></> }

            <Main>
              <ModalContainer />

              { children }
            </Main>
          </MenuProvider>

          <Footer />
        </GlobalProviders>
      </body>
    </html>
  )
}
